### PR TITLE
Updated models.py and admin.py

### PR DESCRIPTION
**Pull request by harshitjsurana**
Added autos and makes model to admin site.
Added minlength validators to avoind junk values by user.

### CODE REVIEW

**Comment by harshitsurana** [comment]
Ok, I will look into the code and then would accept it.

**Comment by harshitsurana** [comment]
Is there any special purpose for minlength validators?

**Comment by harshitjsurana** [comment]
> Is there any special purpose for minlength validators?

Actually while data gets store in database there is a chance somebody use H for Honda and other use H for Hyundai. So minlength will help avoid such ambiguity. min cahracter length can be variable and set accordingly.

**Comment by harshitsurana** [comment]
Ok I got it

**Pull request merged**
